In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
data = pd.read_csv('data.csv')

In [14]:
data.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]

In [20]:
data['y'].replace(4,0,inplace=True)
data['y'].replace(3,0,inplace=True)
data['y'].replace(2,0,inplace=True)
data['y'].replace(5,0,inplace=True)


In [21]:
data.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  0  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  0  
3   -80   -77   -85   -77   -72   -69   -65  0  
4   -12   -32   -41   -65   -83   -89   -73  0  

[5 rows x 180 columns]

In [23]:
x = data.iloc[:,1:-1].values

In [5]:
y = data.iloc[:,-1].values


In [6]:
from sklearn.cross_validation import train_test_split


D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 0)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)

In [10]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [11]:
cm

array([[831,  45,   2,  14,   0],
       [ 37, 136, 226,  26, 505],
       [  7, 103, 274,  34, 482],
       [  1,  68,  90, 429, 317],
       [  0,  18,  81,  61, 813]], dtype=int64)

In [31]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [32]:
cm

array([[ 201, 3507],
       [  48,  844]], dtype=int64)

In [33]:
from sklearn.ensemble import RandomForestClassifier
RF_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
RF_classifier.fit(X_train, y_train)
RF_pred = RF_classifier.predict(X_test)
cm = confusion_matrix(y_test, RF_pred)

In [34]:
cm

array([[ 131, 3577],
       [   8,  884]], dtype=int64)

In [35]:
from sklearn.linear_model import LogisticRegression
lassifier = LogisticRegression(random_state=2)
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
cm = confusion_matrix(y_test,pred)

In [36]:
cm

array([[ 201, 3507],
       [  48,  844]], dtype=int64)

In [37]:
from sklearn.naive_bayes import GaussianNB
NB_classifier = GaussianNB()

NB_classifier.fit(X_train,y_train)

nb_pred = NB_classifier.predict(X_test)

nb_cm = confusion_matrix(y_test, nb_pred)

In [39]:
nb_cm

array([[   0, 3708],
       [   0,  892]], dtype=int64)