In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [77]:
data = pd.read_csv('data.csv')

In [78]:
data.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]

In [79]:
data['y'].replace(4,0,inplace=True)
data['y'].replace(3,0,inplace=True)
data['y'].replace(2,0,inplace=True)
data['y'].replace(5,0,inplace=True)


In [80]:
data.head()

Unnamed: 0   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  0  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  0  
3   -80   -77   -85   -77   -72   -69   -65  0  
4   -12   -32   -41   -65   -83   -89   -73  0  

[5 rows x 180 columns]

In [81]:
x = data.iloc[:,1:-1].values

In [82]:
y = data.iloc[:,-1].values


In [83]:
from sklearn.cross_validation import train_test_split


In [84]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 0)


In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [86]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)

In [87]:
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [88]:
cm

array([[3681,   27],
       [  97,  795]], dtype=int64)

In [89]:
accuracy = (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1]+cm[0][1]+cm[1][0])
precision = (cm[0][0]/(cm[0][0]+cm[0][1]))
recall =(cm[0][0]/(cm[0][0]+cm[1][0]))
specificity = (cm[1][1]/(cm[1][1]+cm[0][1]))
f_measure = 2*(precision*recall)/(precision+recall)

In [90]:
print(accuracy)
print(precision)
print(recall)
print(specificity)
print(f_measure)

0.9730434782608696
0.9927184466019418
0.9743250397035469
0.9671532846715328
0.9834357467272242


In [91]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)
# Predicting the Test set results
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [92]:
cm

array([[3600,  108],
       [ 193,  699]], dtype=int64)

In [93]:
accuracy = (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1]+cm[0][1]+cm[1][0])
precision = (cm[0][0]/(cm[0][0]+cm[0][1]))
recall =(cm[0][0]/(cm[0][0]+cm[1][0]))
specificity = (cm[1][1]/(cm[1][1]+cm[0][1]))
f_measure = 2*(precision*recall)/(precision+recall)

In [94]:
print(accuracy)
print(precision)
print(recall)
print(specificity)
print(f_measure)

0.9345652173913044
0.970873786407767
0.9491167940943844
0.8661710037174721
0.9598720170643914


In [95]:
from sklearn.ensemble import RandomForestClassifier
RF_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
RF_classifier.fit(X_train, y_train)
RF_pred = RF_classifier.predict(X_test)
cm = confusion_matrix(y_test, RF_pred)

In [96]:
cm

array([[3675,   33],
       [ 134,  758]], dtype=int64)

In [97]:
accuracy = (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1]+cm[0][1]+cm[1][0])
precision = (cm[0][0]/(cm[0][0]+cm[0][1]))
recall =(cm[0][0]/(cm[0][0]+cm[1][0]))
specificity = (cm[1][1]/(cm[1][1]+cm[0][1]))
f_measure = 2*(precision*recall)/(precision+recall)

In [98]:
print(accuracy)
print(precision)
print(recall)
print(specificity)
print(f_measure)

0.9636956521739131
0.9911003236245954
0.9648201627723813
0.9582806573957017
0.9777836903019822


In [99]:
from sklearn.linear_model import LogisticRegression
lassifier = LogisticRegression(random_state=2)
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
cm = confusion_matrix(y_test,pred)

In [100]:
cm

array([[3600,  108],
       [ 193,  699]], dtype=int64)

In [101]:
accuracy = (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1]+cm[0][1]+cm[1][0])
precision = (cm[0][0]/(cm[0][0]+cm[0][1]))
recall =(cm[0][0]/(cm[0][0]+cm[1][0]))
specificity = (cm[1][1]/(cm[1][1]+cm[0][1]))
f_measure = 2*(precision*recall)/(precision+recall)

In [102]:
print(accuracy)
print(precision)
print(recall)
print(specificity)
print(f_measure)

0.9345652173913044
0.970873786407767
0.9491167940943844
0.8661710037174721
0.9598720170643914


In [103]:
from sklearn.naive_bayes import GaussianNB
NB_classifier = GaussianNB()

NB_classifier.fit(X_train,y_train)

nb_pred = NB_classifier.predict(X_test)

cm = confusion_matrix(y_test, nb_pred)

In [104]:
cm

array([[3630,   78],
       [ 101,  791]], dtype=int64)

In [105]:
accuracy = (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1]+cm[0][1]+cm[1][0])
precision = (cm[0][0]/(cm[0][0]+cm[0][1]))
recall =(cm[0][0]/(cm[0][0]+cm[1][0]))
specificity = (cm[1][1]/(cm[1][1]+cm[0][1]))
f_measure = 2*(precision*recall)/(precision+recall)

In [106]:
print(accuracy)
print(precision)
print(recall)
print(specificity)
print(f_measure)

0.9610869565217391
0.9789644012944984
0.9729295095148753
0.9102416570771001
0.9759376260250033


In [107]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, y_train)
knn_pred = model.predict(X_test)
cm = confusion_matrix(y_test, knn_pred)

In [108]:
cm

array([[3703,    5],
       [ 381,  511]], dtype=int64)

In [109]:
accuracy = (cm[0][0] + cm[1][1])/(cm[0][0] + cm[1][1]+cm[0][1]+cm[1][0])
precision = (cm[0][0]/(cm[0][0]+cm[0][1]))
recall =(cm[0][0]/(cm[0][0]+cm[1][0]))
specificity = (cm[1][1]/(cm[1][1]+cm[0][1]))
f_measure = 2*(precision*recall)/(precision+recall)

In [110]:
print(accuracy)
print(precision)
print(recall)
print(specificity)
print(f_measure)

0.9160869565217391
0.9986515641855448
0.9067091087169442
0.9903100775193798
0.9504620123203286
